Wip/cache and dramwrapper
yuyuranium/VSD-Project-2022-embedded-sr-system pull request #4
Opened 2022-12-31 16:28 UTC by ShuanSUN

1. Add DRAM_wrapper.sv
2. Add cache folder include L1C_data.sv, L1C_inst.sv, data_array_wrapper.sv, tag_array_wrapper.sv

2022-12-31 17:07 UTC, weilong0512 approved these changes

2023-01-01 03:39 UTC, yuyuranium requested changes
I appreciate the PR. Here are a few of my suggestions. Please take a look, and let me know if you have any further suggestions. :+1:

2023-01-01 03:39 UTC, yuyuranium commented on src/DRAM_wrapper.sv
> +`include "AXI_define.svh"
```suggestion
`include "axi_def.svh"

```
We are using `axi_def.svh` by @0x26rew. (You may apply the suggestion directly by clicking on the button)

2023-01-01 03:39 UTC, yuyuranium commented on src/DRAM_wrapper.sv
> +  always_ff @(posedge clk_i) begin//, negedge !rst_ni
Since we are not going to handle CDC issue, I think we can use **asynchronous**, **active-low** reset instead? (I remember Superlint will report warnings on synchronous reset)

2023-01-01 03:39 UTC, yuyuranium commented on src/DRAM_wrapper.sv
> +  fsm_e state, next_state;
```suggestion
  /*localparam IDLE = 3'd0;
  localparam ACT = 3'd1;
  localparam READ = 3'd2;
  localparam WRITE = 3'd3;
  localparam PRE = 3'd4;
  localparam DELAY = 3'd5;*/
  typedef enum logic [2:0] {
    IDLE, ACT, READ, WRITE, PRE, DELAY
  } fsm_e;
  fsm_e state, next_state;

```
The `logic [2:0]` definition should be added to the `enum` definition.

2023-01-01 03:39 UTC, yuyuranium commented on src/cache/setting.json
> +}
I think the setting file should be put under `.vscode` folder under the project root, which will then be ignored by git.

2023-01-01 03:39 UTC, yuyuranium commented on src/DRAM_wrapper.sv
> +module DRAM_wrapper (
```suggestion
module dram_wrapper (
```
I think it's fine to use all lower case letters in the module name for consistency, even though it is a acronym.
(Also the filename can use `dram_wrapper.sv`)

2023-01-01 03:39 UTC, yuyuranium commented on src/cache/L1C_data.sv
> +module L1C_data (
As we discussed yesterday, I think we'll use my cache for L1 for now. You may remove `L1C_data.sv` and `L1C_inst.sv`, but `data_array_wrapper.sv` and `tag_array_wrapper.sv` can be kept. I'm really sorry for that, since it looks like you have already put some time in and revised many lines of code. :disappointed:

2023-01-02 09:57 UTC, yuyuranium approved these changes
Looks good to me. You may merge when you are ready to.

2023-01-02 13:29 UTC, merged