Wip/rom wrapper&sram wrapper&sctrl wrapper
yuyuranium/VSD-Project-2022-embedded-sr-system pull request #8
Opened 2023-01-03 09:06 UTC by weilong0512

2023-01-03 16:07 UTC, yuyuranium requested changes

2023-01-03 16:07 UTC, yuyuranium commented on src/rom_wrapper.sv
> +  } STATE_q, STATE_d;
I think `state_q` and `state_d` would be good!

2023-01-03 16:07 UTC, yuyuranium commented on src/rom_wrapper.sv
> +  input logic [AXIDataWidth-1:0]  DO_i
Can use lower_snake_case like `do_i`, `a_o`, or `cs_o` for consistency.

2023-01-04 06:32 UTC, weilong0512 commented
coding style fixed, sorry that i take too much time

2023-01-04 08:18 UTC, yuyuranium approved these changes
No worries! Thank you for your hard work :heart:

2023-01-04 08:21 UTC, 0x26rew approved these changes
Good job!

2023-01-04 08:21 UTC, merged